import type {
  ActivityItem,
  Agent,
  ApprovalItem,
  OutputItem,
  PipelineStage,
  Task,
} from "./types";

export const AGENTS: Agent[] = [
  {
    id: "orbit",
    name: "오비트",
    callSign: "ORBIT-00",
    role: "오케스트레이터",
    specialty: "의존성 정리 · 작업 배분",
    status: "working",
    currentTaskId: "SIM-241",
    queueCount: 4,
    load: 82,
    lastActivity: "방금 전",
  },
  {
    id: "probe",
    name: "프로브",
    callSign: "PROBE-17",
    role: "자료조사 에이전트",
    specialty: "표준 · 논문 · 경쟁 제품",
    status: "working",
    currentTaskId: "SIM-238",
    queueCount: 3,
    load: 68,
    lastActivity: "2분 전",
  },
  {
    id: "calc",
    name: "칼크",
    callSign: "CALC-04",
    role: "견적·분석 에이전트",
    specialty: "공수 · 비용 · 성능 모델",
    status: "review",
    currentTaskId: "SIM-233",
    queueCount: 2,
    load: 74,
    lastActivity: "6분 전",
  },
  {
    id: "verify",
    name: "베리파이",
    callSign: "VERIFY-09",
    role: "테스트 에이전트",
    specialty: "시나리오 · 커버리지 · 판정",
    status: "working",
    currentTaskId: "SIM-236",
    queueCount: 3,
    load: 61,
    lastActivity: "4분 전",
  },
  {
    id: "gitmate",
    name: "깃메이트",
    callSign: "GIT-21",
    role: "레포·Git 에이전트",
    specialty: "이슈 구조 · 라벨 · 추적성",
    status: "waiting",
    currentTaskId: "SIM-229",
    queueCount: 1,
    load: 32,
    lastActivity: "18분 전",
  },
  {
    id: "flashx",
    name: "플래시-X",
    callSign: "FLASH-X",
    role: "프레임워크 전문가",
    specialty: "SSD/UFS · 워크로드 모델링",
    status: "review",
    currentTaskId: "SIM-240",
    queueCount: 2,
    load: 57,
    lastActivity: "9분 전",
  },
];

export const INITIAL_TASKS: Task[] = [
  {
    id: "SIM-241",
    title: "UFS 4.1 WriteBooster 정책 변경 영향 정리",
    brief:
      "차기 시뮬레이터 릴리스 범위를 확정하기 위해 캐시 소진 이후의 쓰기 거동과 모델 변경 지점을 정리합니다.",
    priority: "urgent",
    stage: "approval",
    assigneeId: "orbit",
    dueLabel: "오늘 16:00",
    updatedLabel: "8분 전 갱신",
    progress: 92,
    tags: ["UFS 4.1", "WriteBooster", "릴리스"],
    requiredOutput: "변경 영향 요약 + 구현 범위 승인안",
    acceptanceCriteria: [
      "JEDEC 근거와 내부 가정이 구분되어 있다",
      "모델 수정 범위와 제외 범위가 명시되어 있다",
      "릴리스 일정 영향이 주 단위로 제시되어 있다",
    ],
  },
  {
    id: "SIM-238",
    title: "PCIe 5.0 SSD 열 스로틀링 공개 데이터 조사",
    brief:
      "지속 쓰기 구간의 온도-성능 상관관계를 보정할 수 있는 공개 벤치마크와 논문을 수집합니다.",
    priority: "high",
    stage: "research",
    assigneeId: "probe",
    dueLabel: "오늘 18:00",
    updatedLabel: "2분 전 갱신",
    progress: 54,
    tags: ["PCIe 5.0", "Thermal", "Dataset"],
    requiredOutput: "출처 등급이 포함된 근거 매트릭스",
    acceptanceCriteria: [
      "서로 다른 3개 이상 장치군이 포함되어 있다",
      "측정 환경과 한계가 출처별로 표기되어 있다",
      "모델 입력값으로 사용할 수 있는 구간이 표시되어 있다",
    ],
  },
  {
    id: "SIM-236",
    title: "GC 간섭 재현용 혼합 워크로드 테스트 설계",
    brief:
      "랜덤 쓰기와 순차 읽기가 교차할 때 발생하는 GC 간섭을 재현하고 회귀 기준을 정의합니다.",
    priority: "high",
    stage: "test",
    assigneeId: "verify",
    dueLabel: "내일 11:00",
    updatedLabel: "4분 전 갱신",
    progress: 67,
    tags: ["GC", "Workload", "Regression"],
    requiredOutput: "테스트 매트릭스 + 합격/실패 판정식",
    acceptanceCriteria: [
      "큐 깊이와 읽기/쓰기 비율 조합이 정의되어 있다",
      "워밍업과 안정 구간이 구분되어 있다",
      "재현성 오차 허용 범위가 수치로 제시되어 있다",
    ],
  },
  {
    id: "SIM-233",
    title: "Trace replay 모듈 확장 공수 재산정",
    brief:
      "압축 trace와 다중 namespace 지원 요청을 반영해 개발·검증·문서화 공수를 다시 계산합니다.",
    priority: "normal",
    stage: "analysis",
    assigneeId: "calc",
    dueLabel: "내일 15:00",
    updatedLabel: "6분 전 갱신",
    progress: 78,
    tags: ["Estimate", "Trace", "Namespace"],
    requiredOutput: "낙관/기준/보수 3점 견적표",
    acceptanceCriteria: [
      "기능별 개발·테스트 공수가 분리되어 있다",
      "선행 조건과 불확실성 계수가 명시되어 있다",
      "병렬화 가능 구간이 표시되어 있다",
    ],
  },
  {
    id: "SIM-240",
    title: "ZNS zone reset 비용 모델 가정 검토",
    brief:
      "현재 모델의 zone reset 지연 가정이 최신 장치 특성과 맞는지 전문가 검토를 진행합니다.",
    priority: "high",
    stage: "analysis",
    assigneeId: "flashx",
    dueLabel: "오늘 17:30",
    updatedLabel: "9분 전 갱신",
    progress: 43,
    tags: ["ZNS", "Latency", "Assumption"],
    requiredOutput: "가정 검토 메모 + 권장 파라미터 범위",
    acceptanceCriteria: [
      "장치 의존값과 표준 의존값이 분리되어 있다",
      "기본값과 민감도 분석 범위가 제시되어 있다",
      "기존 회귀 결과에 미치는 영향이 설명되어 있다",
    ],
    blockedReason: "벤더 샘플의 reset latency 원시 데이터 수신 대기",
  },
  {
    id: "SIM-229",
    title: "QoS 회귀 개선안 Git 이슈 세트 초안",
    brief:
      "승인된 QoS 개선안을 구현 단위로 쪼개고 담당 팀이 바로 추정할 수 있는 이슈 템플릿을 준비합니다.",
    priority: "normal",
    stage: "issue",
    assigneeId: "gitmate",
    dueLabel: "7월 23일",
    updatedLabel: "18분 전 갱신",
    progress: 84,
    tags: ["Git", "QoS", "Issue Draft"],
    requiredOutput: "의존성 링크가 포함된 Git 이슈 5개",
    acceptanceCriteria: [
      "각 이슈에 범위와 비범위가 명확하다",
      "검증 조건이 체크리스트로 포함되어 있다",
      "선후행 이슈가 링크되어 있다",
    ],
  },
  {
    id: "SIM-244",
    title: "모바일 UFS 지연 분포 기준선 수집 범위 정의",
    brief:
      "제품군별 지연 분포 비교를 시작하기 전 대상 디바이스와 측정 구간을 합의합니다.",
    priority: "normal",
    stage: "inbox",
    assigneeId: "probe",
    dueLabel: "7월 24일",
    updatedLabel: "31분 전 접수",
    progress: 8,
    tags: ["UFS", "Latency", "Baseline"],
    requiredOutput: "조사 범위 제안서",
    acceptanceCriteria: [
      "비교할 제품 세그먼트가 정의되어 있다",
      "필수 측정 항목이 우선순위화되어 있다",
    ],
  },
];

export const PIPELINE_STAGES: PipelineStage[] = [
  { id: "inbox", label: "요청 접수", shortLabel: "접수", description: "목표·범위 확인" },
  { id: "research", label: "자료 조사", shortLabel: "조사", description: "근거·표준 수집" },
  { id: "analysis", label: "견적·분석", shortLabel: "분석", description: "공수·영향 계산" },
  { id: "test", label: "테스트 설계", shortLabel: "테스트", description: "검증 기준 정의" },
  { id: "issue", label: "Git 이슈화", shortLabel: "이슈화", description: "실행 단위 정리" },
  { id: "approval", label: "승인 대기", shortLabel: "승인", description: "사람의 최종 판단" },
];

export const APPROVALS: ApprovalItem[] = [
  { id: "APR-18", taskId: "SIM-241", title: "WriteBooster 모델 변경 범위", requestedBy: "orbit", waitingTime: "22분", decisionKind: "범위 승인", urgency: "urgent" },
  { id: "APR-16", taskId: "SIM-233", title: "Trace replay 3점 견적", requestedBy: "calc", waitingTime: "1시간 14분", decisionKind: "견적 승인", urgency: "normal" },
  { id: "APR-15", taskId: "SIM-229", title: "QoS 개선 이슈 분할안", requestedBy: "gitmate", waitingTime: "2시간 08분", decisionKind: "이슈 게시", urgency: "normal" },
];

export const OUTPUTS: OutputItem[] = [
  { id: "OUT-72", taskId: "SIM-238", title: "PCIe 5.0 열 스로틀링 근거 매트릭스 v0.7", type: "리서치 노트", ownerId: "probe", createdAt: "12분 전", status: "draft" },
  { id: "OUT-70", taskId: "SIM-236", title: "GC 간섭 워크로드 매트릭스", type: "테스트 설계", ownerId: "verify", createdAt: "38분 전", status: "ready" },
  { id: "OUT-68", taskId: "SIM-233", title: "Trace replay 확장 3점 견적", type: "견적서", ownerId: "calc", createdAt: "1시간 전", status: "ready" },
];

export const ACTIVITIES: ActivityItem[] = [
  { id: "LOG-1", actorId: "probe", summary: "신뢰도 A급 출처 2건을 근거표에 추가", time: "2분 전", tone: "teal" },
  { id: "LOG-2", actorId: "verify", summary: "혼합 워크로드 판정식 초안 생성", time: "4분 전", tone: "blue" },
  { id: "LOG-3", actorId: "calc", summary: "기준 견적의 불확실성 계수를 1.25로 조정", time: "6분 전", tone: "amber" },
  { id: "LOG-4", actorId: "flashx", summary: "zone reset 원시 데이터 의존성 표시", time: "9분 전", tone: "slate" },
];
