export const OFFICE_COPY = {
  metadata: {
    title: "AI Office | 팀이 움직이는 디지털 사무실",
    description:
      "한 문장으로 업무를 맡기면 여섯 AI 에이전트가 협업해 결과를 정리하는 디지털 사무실",
    openGraphDescription:
      "오케스트레이터에게 업무를 맡기고 조사, 설계, 견적, 테스트, Git 정리까지 흐름으로 확인하세요.",
    twitterDescription: "여섯 AI 에이전트가 함께 일하는 디지털 사무실",
  },
  header: {
    brand: "AI OFFICE",
    brandDescription: "DIGITAL TEAM FLOOR",
    connections: {
      checking: "연결 확인 중",
      codex: "Codex POC 연결됨",
      opencode: "OpenCode POC 연결됨",
      demo: "안전한 시연 모드",
    },
    clockAria: "현재 시각",
    clockFallback: "--:--",
  },
  hero: {
    eyebrow: "ORBIT DESK",
    title: "무엇을 함께 해결할까요?",
    description:
      "오케스트레이터에게 자연어로 맡기면, 각 자리의 에이전트가 순서대로 협업합니다.",
  },
  composer: {
    label: "오비트에게 요청",
    placeholder: "예: 새 기능 아이디어를 조사하고 구현 범위, 테스트 항목, Git 이슈 초안을 정리해줘",
    hint: "합성 POC 전용입니다. 회사 코드, 비밀값, 내부 문서는 입력하지 마세요.",
    shortcut: "⌘/Ctrl + Enter",
    submit: "오비트에게 맡기기",
    running: "팀이 일하는 중",
    minError: "여덟 글자 이상으로 업무를 알려주세요.",
    maxError: "업무 설명은 2,000자 이내로 작성해 주세요.",
  },
  floor: {
    eyebrow: "LIVE OFFICE FLOOR",
    title: "팀이 움직이는 사무실",
    idleTask: "새 업무를 기다리고 있어요",
    taskLabel: "현재 업무",
    collaborationTable: "중앙 협업 테이블",
    collaborationNote: "handoff point",
    activeSender: "전달 중",
    activeReceiver: "작업 중",
    complete: "정리 완료",
    completeActivity: "팀 결과를 보관함에 정리했어요",
    idle: "자리에서 대기",
  },
  progress: {
    label: "업무 진행 단계",
    idle: "업무를 맡기면 이 흐름으로 진행됩니다.",
    complete: "결과 정리가 끝났습니다. 오른쪽 보관함을 확인하세요.",
    error: "요청을 마치지 못했습니다. 잠시 후 다시 맡겨 주세요.",
  },
  vault: {
    eyebrow: "RESULT ARCHIVE",
    title: "결과 보관함",
    description: "완료된 결과가 한 장씩 쌓입니다.",
    emptyTitle: "아직 보관된 결과가 없어요",
    emptyDescription: "첫 업무를 맡기면 이곳에 결과 카드가 도착합니다.",
    openResult: "결과 열기",
    newResult: "NEW",
    incoming: "결과 도착 중",
  },
  drawer: {
    eyebrow: "COMPLETED BRIEF",
    close: "결과 닫기",
    requestLabel: "맡긴 업무",
    gitLabel: "Git 이슈 초안",
    engineLabel: "실행 엔진",
    roleOutputsLabel: "에이전트 메모",
    workBreakdownLabel: "작업 분해",
    dependenciesLabel: "선행 작업",
    evidenceLabel: "합성 근거",
    noticesLabel: "안내",
    noDependencies: "바로 시작 가능",
    syntheticNotice: "합성 저장소만 사용한 POC 결과입니다.",
  },
  error: {
    title: "사무실 화면을 불러오지 못했어요",
    description: "잠시 후 다시 시도해 주세요. 맡긴 업무는 아직 전송되지 않았습니다.",
    retry: "화면 다시 열기",
  },
  accessibility: {
    skipToMain: "본문으로 건너뛰기",
    workflowUpdates: "업무 진행 알림",
    officeAgents: "AI Office 에이전트 좌석",
    resultCount: "보관된 결과 수",
  },
} as const;
