export const OFFICE_COPY = {
  metadata: {
    title: "Louvre AI 에이전트 개발 오피스",
    description:
      "Louvre 시뮬레이터의 분석팀, 검토팀, 개발팀이 함께 움직이는 AI 에이전트 개발 오피스",
    openGraphDescription:
      "오비트에게 업무를 맡기고 Louvre 분석, 사람 승인, Claude 구현과 PR 검토를 팀별로 확인하세요.",
    twitterDescription: "Louvre의 세 팀이 함께 움직이는 AI 에이전트 개발 오피스",
  },
  header: {
    brand: "LOUVRE AI OFFICE",
    brandDescription: "AI AGENT DEVELOPMENT OFFICE",
    connections: {
      checking: "연결 확인 중",
      codex: "Codex POC 연결됨",
      opencode: "OpenCode POC 연결됨",
      server: "Louvre AI 오피스 단일 서버 연결됨",
      demo: "안전한 시연 모드",
      disconnected: "Louvre AI 오피스 단일 서버 연결 끊김",
    },
    connectionShort: {
      checking: "ZEN 확인 중",
      codex: "Codex 연결",
      opencode: "ZEN 연결",
      server: "서버 연결",
      demo: "시연 모드",
      disconnected: "서버 끊김",
    },
    retryConnection: "서버 연결 다시 확인",
    clockAria: "현재 시각",
    clockFallback: "--:--",
  },
  hero: {
    eyebrow: "ORBIT DESK",
    title: "무엇을 함께 해결할까요?",
    description:
      "오케스트레이터에게 자연어로 맡기면, 각 자리의 에이전트가 순서대로 협업합니다.",
  },
  composer: {
    label: "오비트에게 요청",
    placeholder: "예: 새 기능 아이디어를 조사하고 구현 범위, 테스트 항목, Git 이슈 초안을 정리해줘",
    shortcut: "⌘/Ctrl + Enter",
    submit: "사전 미팅 시작",
    quickSubmit: "바로 맡기기",
    meetingEyebrow: "HUMAN GATE 0 · ORBIT PREFLIGHT",
    meetingTitle: "오비트와 업무를 구체화합니다",
    meetingDescription: "사내 LLM이 요청에 맞춰 영향이 큰 빈칸만 확인하고, 한 장짜리 브리프로 압축합니다.",
    meetingPreparing: "오비트가 요청을 읽고 맞춤 질문을 준비하고 있습니다.",
    meetingModelSource: "사내 LLM 맞춤 질문",
    meetingFallbackSource: "기본 확인 질문",
    meetingFallbackNotice: "사내 LLM 질문을 불러오지 못해 기본 확인 질문으로 미팅을 이어갑니다.",
    reviewTitle: "이 브리프를 분석팀과 Claude가 함께 봅니다",
    reviewDescription: "생각 과정 대신 확정된 요구사항만 전달해 모델 토큰을 아낍니다.",
    confirmBrief: "이 내용으로 분석 시작",
    reviseBrief: "답변 다시 보기",
    cancelMeeting: "미팅 닫기",
    running: "팀이 일하는 중",
    enqueue: "대기열에 추가",
    pocTruth: {
      checking: "현재 POC: 실행 엔진 확인 중 · 역할 흐름은 시각화",
      codex: "현재 POC: Codex 단일 호출 1회 · 역할 흐름은 시각화",
      opencode: "현재 POC: Zen 단일 호출 1회 · 역할 흐름은 시각화",
      server: "단일 서버 · 분석팀과 개발팀의 독립 대기열",
      demo: "현재 시연: 결정론적 결과 · 역할 흐름은 시각화",
      disconnected: "단일 서버 연결이 필요합니다 · 서버 실행 상태를 확인하세요",
    },
    minError: "여덟 글자 이상으로 업무를 알려주세요.",
    maxError: "업무 설명은 2,000자 이내로 작성해 주세요.",
  },
  floor: {
    eyebrow: "LOUVRE AI OFFICE · ENGINEERING HQ",
    title: "Louvre AI 에이전트 개발 오피스",
    idleTask: "새 업무를 기다리고 있어요",
    taskLabel: "현재 업무",
    collaborationTable: "중앙 협업 테이블",
    collaborationNote: "handoff point",
    liveWorkLabel: "지금 진행 중",
    activeAgentsLabel: "현재 작업 중인 에이전트",
    requestInbox: "업무 요청",
    handoffLabel: "업무 전달",
    activeSender: "전달 중",
    activeReceiver: "작업 중",
    complete: "정리 완료",
    completeActivity: "팀 결과를 보관함에 정리했어요",
    idle: "자리에서 대기",
    error: "문제 발생",
    errorActivity: "이 단계에서 작업이 멈췄어요",
  },
  queue: {
    eyebrow: "WORK QUEUE",
    title: "업무 대기열 · 히스토리",
    empty: "맡긴 업무가 여기에 순서대로 쌓입니다.",
    pending: "대기",
    running: "진행 중",
    completed: "완료",
    failed: "문제",
    waitingCount: "건 대기",
    queueLabel: "순차 처리 대기열",
    historyLabel: "최근 히스토리",
    openResult: "완료 결과 열기",
    cancel: "대기 업무 취소",
    clearHistory: "완료 기록 지우기",
    failedAgents: "문제 에이전트",
    full: "POC 대기열은 최대 10건입니다. 대기 업무를 취소하거나 완료될 때까지 기다려 주세요.",
  },
  progress: {
    label: "업무 진행 단계",
    idle: "업무를 맡기면 이 흐름으로 진행됩니다.",
    complete: "결과 정리가 끝났습니다. 바로 결과를 확인하세요.",
    completeTitle: "업무 완료",
    errorTitle: "업무를 마치지 못했어요",
    openResult: "결과 보기",
    waiting: {
      checking: "연결 확인 · 응답 대기",
      codex: "Codex 응답 대기",
      opencode: "Zen 응답 대기",
      demo: "시연 결과 준비",
      disconnected: "Zen 응답 대기",
    },
    elapsedClarification: "로컬 브라우저 경과 시간 · 서버 진행률 아님",
    error: "요청을 마치지 못했습니다. 잠시 후 다시 맡겨 주세요.",
  },
  vault: {
    eyebrow: "RESULT ARCHIVE",
    title: "결과 보관함",
    description: "완료된 결과가 한 장씩 쌓입니다.",
    emptyTitle: "아직 보관된 결과가 없어요",
    emptyDescription: "첫 업무를 맡기면 이곳에 결과 카드가 도착합니다.",
    openResult: "결과 열기",
    newResult: "NEW",
    incoming: "결과 도착 중",
  },
  drawer: {
    eyebrow: "COMPLETED BRIEF",
    close: "결과 닫기",
    requestLabel: "맡긴 업무",
    gitLabel: "Git 이슈 초안",
    engineLabel: "실행 엔진",
    roleOutputsLabel: "에이전트 메모",
    workBreakdownLabel: "작업 분해",
    dependenciesLabel: "선행 작업",
    evidenceLabel: "근거 자료",
    noticesLabel: "안내",
    noDependencies: "바로 시작 가능",
  },
  error: {
    title: "사무실 화면을 불러오지 못했어요",
    description: "잠시 후 다시 시도해 주세요. 맡긴 업무는 아직 전송되지 않았습니다.",
    retry: "화면 다시 열기",
  },
  accessibility: {
    skipToMain: "본문으로 건너뛰기",
    workflowUpdates: "업무 진행 알림",
    officeAgents: "Louvre AI 에이전트 개발 오피스 좌석",
    resultCount: "보관된 결과 수",
  },
} as const;
