import type { OfficeAgent, WorkflowStage } from "./types";

export const OFFICE_AGENTS: readonly OfficeAgent[] = [
  {
    id: "orchestrator",
    name: "오비트",
    role: "오케스트레이터",
    deskLabel: "ORBIT",
    specialty: "업무 분해와 최종 정리",
    seat: "south",
  },
  {
    id: "research",
    name: "딜디",
    role: "DLD · 위키",
    deskLabel: "DLD",
    specialty: ".LLM과 상세 스펙 정리",
    seat: "north-west",
  },
  {
    id: "framework",
    name: "코드-X",
    role: "코드 · 프레임워크",
    deskLabel: "CODE-X",
    specialty: "common·FTL·FIL·HIL 코드 영향 분석",
    seat: "south-west",
  },
  {
    id: "estimate",
    name: "탑뷰",
    role: "TopView · 영향/견적",
    deskLabel: "TOPVIEW",
    specialty: "커맨드별 패킷 흐름과 작업 범위",
    seat: "north",
  },
  {
    id: "test",
    name: "베리파이",
    role: "테스트",
    deskLabel: "VERIFY",
    specialty: "검증 항목과 예외 점검",
    seat: "north-east",
  },
  {
    id: "git",
    name: "핸드오프",
    role: "Claude · Git",
    deskLabel: "HANDOFF",
    specialty: "Claude 코딩팩과 Git 이슈 초안",
    seat: "south-east",
  },
] as const;

export const DEMO_WORKFLOW: readonly WorkflowStage[] = [
  {
    id: "intake",
    label: "업무 접수",
    shortLabel: "접수",
    description: "오케스트레이터가 요청을 읽고 팀의 작업으로 나누고 있습니다.",
    durationMs: 2200,
    senderIds: [],
    receiverIds: ["orchestrator"],
    transfer: { id: "request-in", from: "inbox", to: "orchestrator", route: "inbox-orchestrator" },
    agentActions: { orchestrator: "요청을 읽고 업무를 나누는 중" },
  },
  {
    id: "parallel",
    label: "DLD · 코드 병렬 분석",
    shortLabel: "스펙 · 코드",
    description: "DLD와 코드 분석 에이전트가 상세 스펙과 영향 코드를 동시에 찾고 있습니다.",
    durationMs: 3200,
    senderIds: ["orchestrator"],
    receiverIds: ["research", "framework"],
    transfer: { id: "to-specialists", from: "orchestrator", to: "research", route: "orchestrator-research" },
    agentActions: {
      orchestrator: "두 작업을 동시에 전달하는 중",
      research: ".LLM과 DLD에서 상세 스펙 조사 중",
      framework: "common·FTL·FIL·HIL 영향 코드 분석 중",
    },
  },
  {
    id: "review",
    label: "TopView · 테스트 검토",
    shortLabel: "흐름 · 테스트",
    description: "TopView 흐름과 코드 근거를 바탕으로 작업 범위와 검증 항목을 다듬고 있습니다.",
    durationMs: 3200,
    senderIds: ["research", "framework"],
    receiverIds: ["estimate", "test"],
    transfer: { id: "to-review", from: "research", to: "estimate", route: "research-estimate" },
    agentActions: {
      research: "조사 메모를 전달하는 중",
      framework: "설계 메모를 전달하는 중",
      estimate: "커맨드별 패킷 흐름과 작업 범위 정리 중",
      test: "검증 항목과 예외 상황 점검 중",
    },
  },
  {
    id: "git-draft",
    label: "Claude 인계팩 · Git 이슈",
    shortLabel: "Claude 인계",
    description: "핸드오프 에이전트가 Claude가 바로 코딩할 수 있는 자료와 Git 이슈를 묶고 있습니다.",
    durationMs: 2600,
    senderIds: ["estimate", "test"],
    receiverIds: ["git"],
    transfer: { id: "review-to-git", from: "test", to: "git", route: "test-git" },
    agentActions: {
      estimate: "범위 메모를 전달하는 중",
      test: "검증 메모를 전달하는 중",
      git: "Claude 코딩팩과 Git 이슈를 작성하는 중",
    },
  },
  {
    id: "finalize",
    label: "오케스트레이터 최종 정리",
    shortLabel: "최종 정리",
    description: "오케스트레이터가 모든 결과를 읽기 쉬운 한 장으로 정리하고 있습니다.",
    durationMs: 3000,
    senderIds: ["git"],
    receiverIds: ["orchestrator"],
    transfer: { id: "git-to-orchestrator", from: "git", to: "orchestrator", route: "git-orchestrator" },
    agentActions: {
      git: "완성된 이슈 초안을 전달하는 중",
      orchestrator: "팀의 결과를 한 장으로 정리하는 중",
    },
  },
] as const;

export const REDUCED_MOTION_STAGE_DURATION_MS = 1_800;
